{{- if .Values.canary.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ml-model-chart.fullname" . }}-canary
  labels:
    app: {{ include "ml-model-chart.name" . }}
    release: canary
spec:
  replicas: {{ .Values.canary.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ml-model-chart.name" . }}
      release: canary
  template:
    metadata:
      labels:
        app: {{ include "ml-model-chart.name" . }}
        release: canary
    spec:
{{- include "ml-model-chart.deployment.podSpec" (dict "root" . "release" "canary" "imageTag" .Values.canary.image.tag) | indent 6 }}
{{- end }}
