apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ml-model-chart.fullname" . }}-stable
  labels:
    app: {{ include "ml-model-chart.name" . }}
    release: stable
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ml-model-chart.name" . }}
      release: stable
  template:
    metadata:
      labels:
        app: {{ include "ml-model-chart.name" . }}
        release: stable
    spec:
{{- include "ml-model-chart.deployment.podSpec" (dict "root" . "release" "stable" "imageTag" .Values.image.tag) | indent 6 }}
