{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.adminToken.secretName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "ml-model-chart.fullname" . }}-admin-token
  labels:
    app: {{ include "ml-model-chart.name" . }}
    release: {{ .Release.Name }}
spec:
  refreshInterval: {{ .Values.externalSecrets.adminToken.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.storeRef }}
    kind: SecretStore
  target:
    name: {{ .Values.env.adminTokenSecretName | default (printf "%s-admin-token" (include "ml-model-chart.fullname" .)) }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        {{ .Values.env.adminTokenSecretKey | default "token" }}: "{{ "{{" }} .token {{ "}}" }}"
  data:
    - secretKey: token
      remoteRef:
        key: {{ .Values.externalSecrets.adminToken.secretName }}
        {{- if .Values.externalSecrets.adminToken.secretKey }}
        property: {{ .Values.externalSecrets.adminToken.secretKey }}
        {{- end }}
{{- end -}}

