{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.mlflowCredentials.secretName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "ml-model-chart.fullname" . }}-mlflow-credentials
  labels:
    app: {{ include "ml-model-chart.name" . }}
    release: {{ .Release.Name }}
spec:
  refreshInterval: {{ .Values.externalSecrets.mlflowCredentials.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.storeRef }}
    kind: SecretStore
  target:
    name: {{ .Values.env.mlflow.trackingPasswordSecretName | default (printf "%s-mlflow-credentials" (include "ml-model-chart.fullname" .)) }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        {{ .Values.env.mlflow.trackingPasswordSecretKey | default "password" }}: "{{ "{{" }} .password {{ "}}" }}"
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.mlflowCredentials.secretName }}
        {{- if .Values.externalSecrets.mlflowCredentials.secretKey }}
        property: {{ .Values.externalSecrets.mlflowCredentials.secretKey }}
        {{- end }}
{{- end -}}

