{{- if .Values.canary.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ml-model-chart.fullname" . }}-canary-svc
  labels:
    app: {{ include "ml-model-chart.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ include "ml-model-chart.name" . }}
    release: canary
{{- end }}

